# This is a basic workflow to help you get started with Actions

name: CI



# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'testar-deploy-key'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Create deploy key
        run: |
          # Deploy key
          npm install -g github-deploy-key
          ssh-keygen -m PEM -t rsa -b 4096 -C "harri.seppanen@oaks.se"  -o -f id_rsa
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Generate SSH"
          #gh auth login --scopes "admin:org"
          #gh secret set secret-name
          #gh secret set secret-name < testkey.pub
      # Push changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
